name: KBOT-CICD

on: 
  push:
    branches:
      - develop
env:
  TARGETARCH: amd64
  TARGETOS: linux
  
jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
            fetch-depth: 0

      - name: Run test
        run: make test
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Build&Push
        env:
          APP: "kbot"
          
        run: make image push

  cd:
    name: CD 
    needs: ci
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: echo "VERSION=$(git describe --tags --abbrev=0)-$( git rev-parse --short HEAD)" >> $GITHUB_ENV

      - uses: mikefarah/yq@master
        with:
          cmd: yq -i '.image.tag=strenv(VERSION) | .image.os=strenv(TARGETOS) | .image.arch=strenv(TARGETARCH)' helm/values.yaml
            
      - run: |
         git config user.name github-action
         git config user.email github-action@github.com
         git commit -am "update versin $VERSION"
         git push